import type { Metadata } from 'next';
import { Young_Serif, Outfit } from 'next/font/google';
import './globals.css';

const youngSerif = Young_Serif({
  subsets: ['latin'],
  display: 'swap',
  style: 'normal',
  weight: '400',
  variable: '--font-young-serif',
});

const outfit = Outfit({
  subsets: ['latin'],
  display: 'swap',
  style: 'normal',
  variable: '--font-outfit',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${youngSerif.variable} ${outfit.variable}`}>
        {children}
      </body>
    </html>
  );
}
